remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Generative Methods: \nInvestigating the Use for the Social Study of Science and Technology
description: Workshop at STS-CH Conference 2025, Zurich, Switzerland

sass:
  style: compressed

include:
  - assets